export const SELECT_LOCALISATION = 'SELECT_LOCALISATION';
export const UNSELECT_LOCALISATION = 'UNSELECT_LOCALISATION';
export const SELECT_CULTURE = 'SELECT_CULTURE';
export const SELECT_ATTAQUE = 'SELECT_ATTAQUE';