export const SELECT_LOCALISATION = 'SELECT_LOCALISATION';
export const UNSELECT_LOCALISATION = 'UNSELECT_LOCALISATION';
export const SELECT_CULTURE = 'SELECT_CULTURE';
export const SELECT_ATTAQUE = 'SELECT_ATTAQUE';
export const SET_CULTURES= 'SET_CULTURES'
export const SET_ATTAQUES= 'SET_ATTAQUES'
export const MODIFIE_IMAGES_ATTAQUES='MODIFIE_IMAGES_ATTAQUES'

//action connection
export const ADD_AGRICULTEUR = 'ADD_AGRICULTEUR';
export const ADD_CHERCHEUR = 'ADD_CHERCHEUR';
export const CONNEXION = 'CONNEXION';
export const DECONNEXION = 'DECONNEXION';


export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const UI_ERROR = "UI_ERROR";
export const UI_ERROR_DEL = "UI_ERROR_DEL";




