export const SELECT_LOCALISATION = 'SELECT_LOCALISATION';
export const UNSELECT_LOCALISATION = 'UNSELECT_LOCALISATION';
export const SELECT_CULTURE = 'SELECT_CULTURE';
export const SELECT_ATTAQUE = 'SELECT_ATTAQUE';

//action connection
export const ADD_AGRICULTEUR = 'ADD_AGRICULTEUR';
export const ADD_CHERCHEUR = 'ADD_CHERCHEUR';
export const CONNEXION_CHERCHEUR = 'CONNEXION_CHERCHEUR';
export const CONNEXION_AGRICULTURE = 'CONNEXION_AGRICULTURE';




